### ISSUE TITLE
VS 2013 tutorial 201

### ISSUE THREAD

**Issue by keusam** [libigl/libigl#31]
Hi

I am trying to work with libigl. I could run the first example FileIO but in the second I get some errores when I try to build my solution.

I did: 
* Additional include directories
  * external\glew\include
  * external\AntTweakBar\src
  * external\glfw\include
  * external\AntTweakBar\include
  * eigen-eigen-6b38706d90a9
  * \libigl\include

* AdditionalLibraryDirectories
  * external\glfw\lib\x64
  * external\AntTweakBar\lib

* AdditionalDependencies
  * AntTweakBar.lib
  * glfw3.lib

My errors are:

* Error	44	error C2440: '=' : cannot convert from 'char *' to 'LPWSTR'	c:\users\samuel\downloads\libigl-master\libigl-master\include\igl\file_dialog_open.cpp	49	1	test
* Error	45	error C2440: '=' : cannot convert from 'const char [5]' to 'LPCWSTR'	c:\users\samuel\downloads\libigl-master\libigl-master\include\igl\file_dialog_open.cpp	54	1	test
* Error	46	error C2440: '=' : cannot convert from 'char *' to 'LPWSTR'	c:\users\samuel\downloads\libigl-master\libigl-master\include\igl\file_dialog_save.cpp	51	1	test
* Error	47	error C2440: '=' : cannot convert from 'const char [1]' to 'LPCWSTR'	c:\users\samuel\downloads\libigl-master\libigl-master\include\igl\file_dialog_save.cpp	56	1	test

kind regards and thanks a lot

**Comment by kybio** [comment]
Change 'char' to 'WCHAR'.

**Comment by alecjacobson** [comment]
keusam, did kybio's fix solve your problems?

**Comment by keusam** [comment]
Hi

Sorry for my long response time.
the fix solved two error messages. Now these two are left:

Error	44	error C2440: '=' : cannot convert from 'const char [5]' to 'LPCWSTR'	c:\users\samuel\downloads\libigl-master\libigl-master\include\igl\file_dialog_open.cpp	54	1	test
Error	45	error C2440: '=' : cannot convert from 'const char [1]' to 'LPCWSTR'	c:\users\samuel\downloads\libigl-master\libigl-master\include\igl\file_dialog_save.cpp	56	1	test


To get rid of them I tried to convert the two char arrays myself but this led to another 100 error messages.

**Comment by cap257zero** [comment]
Interesting -- I've got precisely the same four errors, using VS 2012, not for the tutorial example but just trying to construct a Project from scratch that makes use of the viewer.

However, when I run CMake on a tutorial example to build a VS 2012 project that way, I do NOT encounter the errors and the tutorial examples compile and run, and the viewer works. There must be a clue here.

**Comment by cap257zero** [comment]
I think these errors are addressed here:

https://social.msdn.microsoft.com/Forums/vstudio/en-US/c1b08c0a-a803-41c3-ac8c-84eba3be1ddb/faq-cannot-convert-from-const-char-to-lpctstr

The suggested fix of going to Configuration Properties > General and changing Character Set to "Use Multi-Byte Character Set" seems to have worked for me to eliminate these particular errors (using VS 2012).

**Comment by keusam** [comment]
Thanks cap
But unfortunately this leads to the same 100 errors as with my fix. So I think, I got a problem with glew:
Sorry for the huge list

Error	101	error LNK2019: unresolved external symbol __imp__glBindTexture@8 referenced in function "public: void __thiscall igl::OpenGL_state::bind_mesh(void)" (?bind_mesh@OpenGL_state@igl@@QAEXXZ)	C:\Users\Samuel\Documents\Visual Studio 2013\Projects\test\test\test.obj	test
Error	102	error LNK2019: unresolved external symbol __imp__glClear@4 referenced in function "public: void __thiscall igl::ViewerCore::clear_framebuffers(void)" (?clear_framebuffers@ViewerCore@igl@@QAEXXZ)	C:\Users\Samuel\Documents\Visual Studio 2013\Projects\test\test\test.obj	test
Error	103	error LNK2019: unresolved external symbol __imp__glClearColor@16 referenced in function "public: void __thiscall igl::ViewerCore::clear_framebuffers(void)" (?clear_framebuffers@ViewerCore@igl@@QAEXXZ)	C:\Users\Samuel\Documents\Visual Studio 2013\Projects\test\test\test.obj	test
Error	104	error LNK2019: unresolved external symbol __imp__glDeleteTextures@8 referenced in function "public: void __thiscall igl::OpenGL_state::free_buffers(void)" (?free_buffers@OpenGL_state@igl@@QAEXXZ)	C:\Users\Samuel\Documents\Visual Studio 2013\Projects\test\test\test.obj	test
Error	105	error LNK2019: unresolved external symbol __imp__glDepthMask@4 referenced in function "public: void __thiscall igl::TextRenderer::BeginDraw(class Eigen::Matrix<float,4,4,0,4,4> const &,class Eigen::Matrix<float,4,4,0,4,4> const &,class Eigen::Matrix<float,4,1,0,4,1> const &,float)" (?BeginDraw@TextRenderer@igl@@QAEXABV?$Matrix@M$03$03$0A@$03$03@Eigen@@0ABV?$Matrix@M$03$00$0A@$03$00@4@M@Z)	C:\Users\Samuel\Documents\Visual Studio 2013\Projects\test\test\test.obj	test
Error	106	error LNK2019: unresolved external symbol __imp__glDisable@4 referenced in function "public: void __thiscall igl::ViewerCore::draw(class igl::ViewerData &,class igl::OpenGL_state &)" (?draw@ViewerCore@igl@@QAEXAAVViewerData@2@AAVOpenGL_state@2@@Z)	C:\Users\Samuel\Documents\Visual Studio 2013\Projects\test\test\test.obj	test
Error	107	error LNK2019: unresolved external symbol __imp__glDrawElements@16 referenced in function "public: void __thiscall igl::OpenGL_state::draw_mesh(bool)" (?draw_mesh@OpenGL_state@igl@@QAEX_N@Z)	C:\Users\Samuel\Documents\Visual Studio 2013\Projects\test\test\test.obj	test
Error	108	error LNK2019: unresolved external symbol __imp__glEnable@4 referenced in function "public: void __thiscall igl::TextRenderer::BeginDraw(class Eigen::Matrix<float,4,4,0,4,4> const &,class Eigen::Matrix<float,4,4,0,4,4> const &,class Eigen::Matrix<float,4,1,0,4,1> const &,float)" (?BeginDraw@TextRenderer@igl@@QAEXABV?$Matrix@M$03$03$0A@$03$03@Eigen@@0ABV?$Matrix@M$03$00$0A@$03$00@4@M@Z)	C:\Users\Samuel\Documents\Visual Studio 2013\Projects\test\test\test.obj	test
Error	109	error LNK2019: unresolved external symbol __imp__glGenTextures@8 referenced in function "public: void __thiscall igl::OpenGL_state::init_buffers(void)" (?init_buffers@OpenGL_state@igl@@QAEXXZ)	C:\Users\Samuel\Documents\Visual Studio 2013\Projects\test\test\test.obj	test
Error	110	error LNK2019: unresolved external symbol __imp__glLineWidth@4 referenced in function "public: void __thiscall igl::ViewerCore::draw(class igl::ViewerData &,class igl::OpenGL_state &)" (?draw@ViewerCore@igl@@QAEXAAVViewerData@2@AAVOpenGL_state@2@@Z)	C:\Users\Samuel\Documents\Visual Studio 2013\Projects\test\test\test.obj	test
Error	111	error LNK2019: unresolved external symbol __imp__glPointSize@4 referenced in function "public: void __thiscall igl::ViewerCore::draw(class igl::ViewerData &,class igl::OpenGL_state &)" (?draw@ViewerCore@igl@@QAEXAAVViewerData@2@AAVOpenGL_state@2@@Z)	C:\Users\Samuel\Documents\Visual Studio 2013\Projects\test\test\test.obj	test
Error	112	error LNK2019: unresolved external symbol __imp__glPolygonMode@8 referenced in function "public: void __thiscall igl::OpenGL_state::draw_mesh(bool)" (?draw_mesh@OpenGL_state@igl@@QAEX_N@Z)	C:\Users\Samuel\Documents\Visual Studio 2013\Projects\test\test\test.obj	test
Error	113	error LNK2019: unresolved external symbol __imp__glPolygonOffset@8 referenced in function "public: void __thiscall igl::OpenGL_state::draw_mesh(bool)" (?draw_mesh@OpenGL_state@igl@@QAEX_N@Z)	C:\Users\Samuel\Documents\Visual Studio 2013\Projects\test\test\test.obj	test
Error	114	error LNK2019: unresolved external symbol __imp__glTexImage2D@36 referenced in function "public: void __thiscall igl::OpenGL_state::bind_mesh(void)" (?bind_mesh@OpenGL_state@igl@@QAEXXZ)	C:\Users\Samuel\Documents\Visual Studio 2013\Projects\test\test\test.obj	test
Error	115	error LNK2019: unresolved external symbol __imp__glTexParameteri@12 referenced in function "public: void __thiscall igl::OpenGL_state::bind_mesh(void)" (?bind_mesh@OpenGL_state@igl@@QAEXXZ)	C:\Users\Samuel\Documents\Visual Studio 2013\Projects\test\test\test.obj	test
Error	116	error LNK2019: unresolved external symbol __imp__glViewport@16 referenced in function "public: void __thiscall igl::ViewerCore::draw(class igl::ViewerData &,class igl::OpenGL_state &)" (?draw@ViewerCore@igl@@QAEXAAVViewerData@2@AAVOpenGL_state@2@@Z)	C:\Users\Samuel\Documents\Visual Studio 2013\Projects\test\test\test.obj	test
Error	117	error LNK2019: unresolved external symbol _glewInit@0 referenced in function "public: int __thiscall igl::Viewer::launch(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >)" (?launch@Viewer@igl@@QAEHV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z)	C:\Users\Samuel\Documents\Visual Studio 2013\Projects\test\test\test.obj	test
Error	118	error LNK2019: unresolved external symbol _glewGetErrorString@4 referenced in function "public: int __thiscall igl::Viewer::launch(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >)" (?launch@Viewer@igl@@QAEHV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z)	C:\Users\Samuel\Documents\Visual Studio 2013\Projects\test\test\test.obj	test
Error	119	error LNK2019: unresolved external symbol _glewGetString@4 referenced in function "public: int __thiscall igl::Viewer::launch(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >)" (?launch@Viewer@igl@@QAEHV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z)	C:\Users\Samuel\Documents\Visual Studio 2013\Projects\test\test\test.obj	test
Error	120	error LNK2019: unresolved external symbol "__declspec(dllimport) public: virtual int __thiscall CTwGraphOpenGLCore::Init(void)" (__imp_?Init@CTwGraphOpenGLCore@@UAEHXZ) referenced in function "public: virtual int __thiscall igl::TextRenderer::Init(void)" (?Init@TextRenderer@igl@@UAEHXZ)	C:\Users\Samuel\Documents\Visual Studio 2013\Projects\test\test\test.obj	test
Error	121	error LNK2019: unresolved external symbol "__declspec(dllimport) public: virtual int __thiscall CTwGraphOpenGLCore::Shut(void)" (__imp_?Shut@CTwGraphOpenGLCore@@UAEHXZ) referenced in function "public: virtual int __thiscall igl::TextRenderer::Shut(void)" (?Shut@TextRenderer@igl@@UAEHXZ)	C:\Users\Samuel\Documents\Visual Studio 2013\Projects\test\test\test.obj	test
Error	122	error LNK2019: unresolved external symbol "__declspec(dllimport) public: virtual void __thiscall CTwGraphOpenGLCore::BeginDraw(int,int)" (__imp_?BeginDraw@CTwGraphOpenGLCore@@UAEXHH@Z) referenced in function "public: void __thiscall igl::TextRenderer::BeginDraw(class Eigen::Matrix<float,4,4,0,4,4> const &,class Eigen::Matrix<float,4,4,0,4,4> const &,class Eigen::Matrix<float,4,1,0,4,1> const &,float)" (?BeginDraw@TextRenderer@igl@@QAEXABV?$Matrix@M$03$03$0A@$03$03@Eigen@@0ABV?$Matrix@M$03$00$0A@$03$00@4@M@Z)	C:\Users\Samuel\Documents\Visual Studio 2013\Projects\test\test\test.obj	test
Error	123	error LNK2019: unresolved external symbol "__declspec(dllimport) public: virtual void __thiscall CTwGraphOpenGLCore::EndDraw(void)" (__imp_?EndDraw@CTwGraphOpenGLCore@@UAEXXZ) referenced in function "public: virtual void __thiscall igl::TextRenderer::EndDraw(void)" (?EndDraw@TextRenderer@igl@@UAEXXZ)	C:\Users\Samuel\Documents\Visual Studio 2013\Projects\test\test\test.obj	test
Error	124	error LNK2019: unresolved external symbol "__declspec(dllimport) public: virtual void __thiscall CTwGraphOpenGLCore::DrawText(void *,int,int,unsigned int,unsigned int)" (__imp_?DrawText@CTwGraphOpenGLCore@@UAEXPAXHHII@Z) referenced in function "public: void __thiscall igl::TextRenderer::DrawText(class Eigen::Matrix<double,3,1,0,3,1>,class Eigen::Matrix<double,3,1,0,3,1>,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?DrawText@TextRenderer@igl@@QAEXV?$Matrix@N$02$00$0A@$02$00@Eigen@@0ABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z)	C:\Users\Samuel\Documents\Visual Studio 2013\Projects\test\test\test.obj	test
Error	125	error LNK2019: unresolved external symbol _glfwInit referenced in function "public: int __thiscall igl::Viewer::launch(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >)" (?launch@Viewer@igl@@QAEHV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z)	C:\Users\Samuel\Documents\Visual Studio 2013\Projects\test\test\test.obj	test
Error	126	error LNK2019: unresolved external symbol _glfwTerminate referenced in function "public: int __thiscall igl::Viewer::launch(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >)" (?launch@Viewer@igl@@QAEHV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z)	C:\Users\Samuel\Documents\Visual Studio 2013\Projects\test\test\test.obj	test
Error	127	error LNK2019: unresolved external symbol _glfwSetErrorCallback referenced in function "public: int __thiscall igl::Viewer::launch(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >)" (?launch@Viewer@igl@@QAEHV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z)	C:\Users\Samuel\Documents\Visual Studio 2013\Projects\test\test\test.obj	test
Error	128	error LNK2019: unresolved external symbol _glfwWindowHint referenced in function "public: int __thiscall igl::Viewer::launch(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >)" (?launch@Viewer@igl@@QAEHV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z)	C:\Users\Samuel\Documents\Visual Studio 2013\Projects\test\test\test.obj	test
Error	129	error LNK2019: unresolved external symbol _glfwCreateWindow referenced in function "public: int __thiscall igl::Viewer::launch(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >)" (?launch@Viewer@igl@@QAEHV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z)	C:\Users\Samuel\Documents\Visual Studio 2013\Projects\test\test\test.obj	test
Error	130	error LNK2019: unresolved external symbol _glfwDestroyWindow referenced in function "public: int __thiscall igl::Viewer::launch(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >)" (?launch@Viewer@igl@@QAEHV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z)	C:\Users\Samuel\Documents\Visual Studio 2013\Projects\test\test\test.obj	test
Error	131	error LNK2019: unresolved external symbol _glfwWindowShouldClose referenced in function "public: int __thiscall igl::Viewer::launch(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >)" (?launch@Viewer@igl@@QAEHV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z)	C:\Users\Samuel\Documents\Visual Studio 2013\Projects\test\test\test.obj	test
Error	132	error LNK2019: unresolved external symbol _glfwSetWindowShouldClose referenced in function "void __cdecl glfw_key_callback(struct GLFWwindow *,int,int,int,int)" (?glfw_key_callback@@YAXPAUGLFWwindow@@HHHH@Z)	C:\Users\Samuel\Documents\Visual Studio 2013\Projects\test\test\test.obj	test
Error	133	error LNK2019: unresolved external symbol _glfwGetWindowSize referenced in function "public: int __thiscall igl::Viewer::launch(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >)" (?launch@Viewer@igl@@QAEHV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z)	C:\Users\Samuel\Documents\Visual Studio 2013\Projects\test\test\test.obj	test
Error	134	error LNK2019: unresolved external symbol _glfwGetFramebufferSize referenced in function "public: int __thiscall igl::Viewer::launch(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >)" (?launch@Viewer@igl@@QAEHV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z)	C:\Users\Samuel\Documents\Visual Studio 2013\Projects\test\test\test.obj	test
Error	135	error LNK2019: unresolved external symbol _glfwSetWindowSizeCallback referenced in function "public: int __thiscall igl::Viewer::launch(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >)" (?launch@Viewer@igl@@QAEHV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z)	C:\Users\Samuel\Documents\Visual Studio 2013\Projects\test\test\test.obj	test
Error	136	error LNK2019: unresolved external symbol _glfwPollEvents referenced in function "public: int __thiscall igl::Viewer::launch(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >)" (?launch@Viewer@igl@@QAEHV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z)	C:\Users\Samuel\Documents\Visual Studio 2013\Projects\test\test\test.obj	test
Error	137	error LNK2019: unresolved external symbol _glfwWaitEvents referenced in function "public: int __thiscall igl::Viewer::launch(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >)" (?launch@Viewer@igl@@QAEHV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z)	C:\Users\Samuel\Documents\Visual Studio 2013\Projects\test\test\test.obj	test
Error	138	error LNK2019: unresolved external symbol _glfwSetInputMode referenced in function "public: int __thiscall igl::Viewer::launch(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >)" (?launch@Viewer@igl@@QAEHV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z)	C:\Users\Samuel\Documents\Visual Studio 2013\Projects\test\test\test.obj	test
Error	139	error LNK2019: unresolved external symbol _glfwSetKeyCallback referenced in function "public: int __thiscall igl::Viewer::launch(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >)" (?launch@Viewer@igl@@QAEHV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z)	C:\Users\Samuel\Documents\Visual Studio 2013\Projects\test\test\test.obj	test
Error	140	error LNK2019: unresolved external symbol _glfwSetCharCallback referenced in function "public: int __thiscall igl::Viewer::launch(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >)" (?launch@Viewer@igl@@QAEHV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z)	C:\Users\Samuel\Documents\Visual Studio 2013\Projects\test\test\test.obj	test
Error	141	error LNK2019: unresolved external symbol _glfwSetMouseButtonCallback referenced in function "public: int __thiscall igl::Viewer::launch(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >)" (?launch@Viewer@igl@@QAEHV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z)	C:\Users\Samuel\Documents\Visual Studio 2013\Projects\test\test\test.obj	test
Error	142	error LNK2019: unresolved external symbol _glfwSetCursorPosCallback referenced in function "public: int __thiscall igl::Viewer::launch(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >)" (?launch@Viewer@igl@@QAEHV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z)	C:\Users\Samuel\Documents\Visual Studio 2013\Projects\test\test\test.obj	test
Error	143	error LNK2019: unresolved external symbol _glfwSetScrollCallback referenced in function "public: int __thiscall igl::Viewer::launch(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >)" (?launch@Viewer@igl@@QAEHV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z)	C:\Users\Samuel\Documents\Visual Studio 2013\Projects\test\test\test.obj	test
Error	144	error LNK2019: unresolved external symbol _glfwMakeContextCurrent referenced in function "public: int __thiscall igl::Viewer::launch(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >)" (?launch@Viewer@igl@@QAEHV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z)	C:\Users\Samuel\Documents\Visual Studio 2013\Projects\test\test\test.obj	test
Error	145	error LNK2019: unresolved external symbol _glfwSwapBuffers referenced in function "public: int __thiscall igl::Viewer::launch(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >)" (?launch@Viewer@igl@@QAEHV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z)	C:\Users\Samuel\Documents\Visual Studio 2013\Projects\test\test\test.obj	test
Error	146	error LNK2001: unresolved external symbol "public: virtual void __thiscall CTwGraphOpenGLCore::BeginDraw(int,int)" (?BeginDraw@CTwGraphOpenGLCore@@UAEXHH@Z)	C:\Users\Samuel\Documents\Visual Studio 2013\Projects\test\test\test.obj	test
Error	147	error LNK2001: unresolved external symbol "public: virtual void __thiscall CTwGraphOpenGLCore::BuildText(void *,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const *,unsigned int *,unsigned int *,int,struct CTexFont const *,int,int)" (?BuildText@CTwGraphOpenGLCore@@UAEXPAXPBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PAI2HPBUCTexFont@@HH@Z)	C:\Users\Samuel\Documents\Visual Studio 2013\Projects\test\test\test.obj	test
Error	148	error LNK2001: unresolved external symbol "public: virtual void __thiscall CTwGraphOpenGLCore::ChangeViewport(int,int,int,int,int,int)" (?ChangeViewport@CTwGraphOpenGLCore@@UAEXHHHHHH@Z)	C:\Users\Samuel\Documents\Visual Studio 2013\Projects\test\test\test.obj	test
Error	149	error LNK2001: unresolved external symbol "public: virtual void __thiscall CTwGraphOpenGLCore::DeleteTextObj(void *)" (?DeleteTextObj@CTwGraphOpenGLCore@@UAEXPAX@Z)	C:\Users\Samuel\Documents\Visual Studio 2013\Projects\test\test\test.obj	test
Error	150	error LNK2001: unresolved external symbol "public: virtual void __thiscall CTwGraphOpenGLCore::DrawLine(int,int,int,int,unsigned int,unsigned int,bool)" (?DrawLine@CTwGraphOpenGLCore@@UAEXHHHHII_N@Z)	C:\Users\Samuel\Documents\Visual Studio 2013\Projects\test\test\test.obj	test
Error	151	error LNK2001: unresolved external symbol "public: virtual void __thiscall CTwGraphOpenGLCore::DrawLine(int,int,int,int,unsigned int,bool)" (?DrawLine@CTwGraphOpenGLCore@@UAEXHHHHI_N@Z)	C:\Users\Samuel\Documents\Visual Studio 2013\Projects\test\test\test.obj	test
Error	152	error LNK2001: unresolved external symbol "public: virtual void __thiscall CTwGraphOpenGLCore::DrawRect(int,int,int,int,unsigned int)" (?DrawRect@CTwGraphOpenGLCore@@UAEXHHHHI@Z)	C:\Users\Samuel\Documents\Visual Studio 2013\Projects\test\test\test.obj	test
Error	153	error LNK2001: unresolved external symbol "public: virtual void __thiscall CTwGraphOpenGLCore::DrawRect(int,int,int,int,unsigned int,unsigned int,unsigned int,unsigned int)" (?DrawRect@CTwGraphOpenGLCore@@UAEXHHHHIIII@Z)	C:\Users\Samuel\Documents\Visual Studio 2013\Projects\test\test\test.obj	test
Error	154	error LNK2001: unresolved external symbol "public: virtual void __thiscall CTwGraphOpenGLCore::DrawText(void *,int,int,unsigned int,unsigned int)" (?DrawText@CTwGraphOpenGLCore@@UAEXPAXHHII@Z)	C:\Users\Samuel\Documents\Visual Studio 2013\Projects\test\test\test.obj	test
Error	155	error LNK2001: unresolved external symbol "public: virtual void __thiscall CTwGraphOpenGLCore::DrawTriangles(int,int *,unsigned int *,enum ITwGraph::Cull)" (?DrawTriangles@CTwGraphOpenGLCore@@UAEXHPAHPAIW4Cull@ITwGraph@@@Z)	C:\Users\Samuel\Documents\Visual Studio 2013\Projects\test\test\test.obj	test
Error	156	error LNK2001: unresolved external symbol "public: virtual void __thiscall CTwGraphOpenGLCore::EndDraw(void)" (?EndDraw@CTwGraphOpenGLCore@@UAEXXZ)	C:\Users\Samuel\Documents\Visual Studio 2013\Projects\test\test\test.obj	test
Error	157	error LNK2001: unresolved external symbol "public: virtual int __thiscall CTwGraphOpenGLCore::Init(void)" (?Init@CTwGraphOpenGLCore@@UAEHXZ)	C:\Users\Samuel\Documents\Visual Studio 2013\Projects\test\test\test.obj	test
Error	158	error LNK2001: unresolved external symbol "public: virtual bool __thiscall CTwGraphOpenGLCore::IsDrawing(void)" (?IsDrawing@CTwGraphOpenGLCore@@UAE_NXZ)	C:\Users\Samuel\Documents\Visual Studio 2013\Projects\test\test\test.obj	test
Error	159	error LNK2001: unresolved external symbol "public: virtual void * __thiscall CTwGraphOpenGLCore::NewTextObj(void)" (?NewTextObj@CTwGraphOpenGLCore@@UAEPAXXZ)	C:\Users\Samuel\Documents\Visual Studio 2013\Projects\test\test\test.obj	test
Error	160	error LNK2001: unresolved external symbol "public: virtual void __thiscall CTwGraphOpenGLCore::Restore(void)" (?Restore@CTwGraphOpenGLCore@@UAEXXZ)	C:\Users\Samuel\Documents\Visual Studio 2013\Projects\test\test\test.obj	test
Error	161	error LNK2001: unresolved external symbol "public: virtual void __thiscall CTwGraphOpenGLCore::RestoreViewport(void)" (?RestoreViewport@CTwGraphOpenGLCore@@UAEXXZ)	C:\Users\Samuel\Documents\Visual Studio 2013\Projects\test\test\test.obj	test
Error	162	error LNK2001: unresolved external symbol "public: virtual void __thiscall CTwGraphOpenGLCore::SetScissor(int,int,int,int)" (?SetScissor@CTwGraphOpenGLCore@@UAEXHHHH@Z)	C:\Users\Samuel\Documents\Visual Studio 2013\Projects\test\test\test.obj	test
Error	163	error LNK2001: unresolved external symbol "public: virtual int __thiscall CTwGraphOpenGLCore::Shut(void)" (?Shut@CTwGraphOpenGLCore@@UAEHXZ)	C:\Users\Samuel\Documents\Visual Studio 2013\Projects\test\test\test.obj	test
Error	164	error LNK2001: unresolved external symbol ___glewActiveTexture	C:\Users\Samuel\Documents\Visual Studio 2013\Projects\test\test\test.obj	test
Error	165	error LNK2001: unresolved external symbol ___glewBindBuffer	C:\Users\Samuel\Documents\Visual Studio 2013\Projects\test\test\test.obj	test
Error	166	error LNK2001: unresolved external symbol ___glewBufferData	C:\Users\Samuel\Documents\Visual Studio 2013\Projects\test\test\test.obj	test
Error	167	error LNK2001: unresolved external symbol ___glewDeleteBuffers	C:\Users\Samuel\Documents\Visual Studio 2013\Projects\test\test\test.obj	test
Error	168	error LNK2001: unresolved external symbol ___glewGenBuffers	C:\Users\Samuel\Documents\Visual Studio 2013\Projects\test\test\test.obj	test
Error	169	error LNK2001: unresolved external symbol ___glewAttachShader	C:\Users\Samuel\Documents\Visual Studio 2013\Projects\test\test\test.obj	test
Error	170	error LNK2001: unresolved external symbol ___glewBindAttribLocation	C:\Users\Samuel\Documents\Visual Studio 2013\Projects\test\test\test.obj	test
Error	171	error LNK2001: unresolved external symbol ___glewCompileShader	C:\Users\Samuel\Documents\Visual Studio 2013\Projects\test\test\test.obj	test
Error	172	error LNK2001: unresolved external symbol ___glewCreateProgram	C:\Users\Samuel\Documents\Visual Studio 2013\Projects\test\test\test.obj	test
Error	173	error LNK2001: unresolved external symbol ___glewCreateShader	C:\Users\Samuel\Documents\Visual Studio 2013\Projects\test\test\test.obj	test
Error	174	error LNK2001: unresolved external symbol ___glewDeleteProgram	C:\Users\Samuel\Documents\Visual Studio 2013\Projects\test\test\test.obj	test
Error	175	error LNK2001: unresolved external symbol ___glewDeleteShader	C:\Users\Samuel\Documents\Visual Studio 2013\Projects\test\test\test.obj	test
Error	176	error LNK2001: unresolved external symbol ___glewDisableVertexAttribArray	C:\Users\Samuel\Documents\Visual Studio 2013\Projects\test\test\test.obj	test
Error	177	error LNK2001: unresolved external symbol ___glewEnableVertexAttribArray	C:\Users\Samuel\Documents\Visual Studio 2013\Projects\test\test\test.obj	test
Error	178	error LNK2001: unresolved external symbol ___glewGetAttribLocation	C:\Users\Samuel\Documents\Visual Studio 2013\Projects\test\test\test.obj	test
Error	179	error LNK2001: unresolved external symbol ___glewGetProgramInfoLog	C:\Users\Samuel\Documents\Visual Studio 2013\Projects\test\test\test.obj	test
Error	180	error LNK2001: unresolved external symbol ___glewGetProgramiv	C:\Users\Samuel\Documents\Visual Studio 2013\Projects\test\test\test.obj	test
Error	181	error LNK2001: unresolved external symbol ___glewGetShaderInfoLog	C:\Users\Samuel\Documents\Visual Studio 2013\Projects\test\test\test.obj	test
Error	182	error LNK2001: unresolved external symbol ___glewGetShaderiv	C:\Users\Samuel\Documents\Visual Studio 2013\Projects\test\test\test.obj	test
Error	183	error LNK2001: unresolved external symbol ___glewGetUniformLocation	C:\Users\Samuel\Documents\Visual Studio 2013\Projects\test\test\test.obj	test
Error	184	error LNK2001: unresolved external symbol ___glewLinkProgram	C:\Users\Samuel\Documents\Visual Studio 2013\Projects\test\test\test.obj	test
Error	185	error LNK2001: unresolved external symbol ___glewShaderSource	C:\Users\Samuel\Documents\Visual Studio 2013\Projects\test\test\test.obj	test
Error	186	error LNK2001: unresolved external symbol ___glewUniform1f	C:\Users\Samuel\Documents\Visual Studio 2013\Projects\test\test\test.obj	test
Error	187	error LNK2001: unresolved external symbol ___glewUniform1i	C:\Users\Samuel\Documents\Visual Studio 2013\Projects\test\test\test.obj	test
Error	188	error LNK2001: unresolved external symbol ___glewUniform3fv	C:\Users\Samuel\Documents\Visual Studio 2013\Projects\test\test\test.obj	test
Error	189	error LNK2001: unresolved external symbol ___glewUniform4f	C:\Users\Samuel\Documents\Visual Studio 2013\Projects\test\test\test.obj	test
Error	190	error LNK2001: unresolved external symbol ___glewUniformMatrix4fv	C:\Users\Samuel\Documents\Visual Studio 2013\Projects\test\test\test.obj	test
Error	191	error LNK2001: unresolved external symbol ___glewUseProgram	C:\Users\Samuel\Documents\Visual Studio 2013\Projects\test\test\test.obj	test
Error	192	error LNK2001: unresolved external symbol ___glewVertexAttribPointer	C:\Users\Samuel\Documents\Visual Studio 2013\Projects\test\test\test.obj	test
Error	193	error LNK2001: unresolved external symbol ___glewBindFragDataLocation	C:\Users\Samuel\Documents\Visual Studio 2013\Projects\test\test\test.obj	test
Error	194	error LNK2001: unresolved external symbol ___glewProgramParameteri	C:\Users\Samuel\Documents\Visual Studio 2013\Projects\test\test\test.obj	test
Error	195	error LNK2001: unresolved external symbol ___glewBindVertexArray	C:\Users\Samuel\Documents\Visual Studio 2013\Projects\test\test\test.obj	test
Error	196	error LNK2001: unresolved external symbol ___glewDeleteVertexArrays	C:\Users\Samuel\Documents\Visual Studio 2013\Projects\test\test\test.obj	test
Error	197	error LNK2001: unresolved external symbol ___glewGenVertexArrays	C:\Users\Samuel\Documents\Visual Studio 2013\Projects\test\test\test.obj	test
Error	198	error LNK2001: unresolved external symbol _glewExperimental	C:\Users\Samuel\Documents\Visual Studio 2013\Projects\test\test\test.obj	test
Error	199	error LNK2001: unresolved external symbol "__declspec(dllimport) struct CTexFont * g_DefaultNormalFont" (__imp_?g_DefaultNormalFont@@3PAUCTexFont@@A)	C:\Users\Samuel\Documents\Visual Studio 2013\Projects\test\test\test.obj	test
Error	200	error LNK1120: 99 unresolved externals	C:\Users\Samuel\Documents\Visual Studio 2013\Projects\test\Debug\test.exe	test

**Comment by cap257zero** [comment]
I'm in a similar boat. I opened a recent issue about this.

I've got nothing to offer you at the moment but I'll let you know if I get anywhere.

**Comment by cap257zero** [comment]
Okay these comments relate to Visual Studio 2012 and also not specifically to a tutorial example but to code built from scratch that launches the viewer, but I think it will still apply. I'll describe what worked for me.

I think the problems have something to do with the Debug/Release stuff going on in Visual Studio. I don't really know for sure. So try not using any precompiled binaries. Build them all yourself in Visual Studio (details below).

So below, we are going to do everything in Debug mode. If I forget to mention it, it's always all Debug. Basically we need glfw, AntTweakBar, and glew.

GLFW

Do you know how to use CMake to build this? Roughly, do the following (assuming you've installed CMake). In a command prompt, navigate to external\glew and make a new folder called "build". In the prompt, navigate into build, and then type the command

cmake .. -G "Visual Studio 11"

(the 11 there is for Visual Studio 2012).

This makes a Visual Studio solution inside "build", as well as several projects.
Open the solution in Visual Studio and Build Solution (in Debug). The effect of all this is that now there is a directory

glfw\build\src\Debug

and inside that directory is "glfw3.lib". That's the one we'll eventually link to.

ANTTWEAKBAR

This is even easier, because inside the folder external\AntTweakBar\src there is a ready-made Visual Studio solution called AntTweakBar_VS2012. (Probably you could update it in VS2013 to a 2013 project....)

Open in VS and Build Solution (in Debug). Now there is a directory

external\AntTweakBar\lib\debug

in which we have AntTweakBar.dll and AntTweakBar.lib, both of which we will need. (And don't use or link to the versions in the external\AntTweakBar\lib directory.)

GLEW

You don't have to do anything yet with glew.

Okay now you can set up a Project/Solution from scratch that's going to use and launch the viewer, e.g. something like

#include <igl/viewer/Viewer.h>
...
igl::Viewer viewer;
...
viewer.launch();

and so on. A couple of miscellaneous things for the project:

Configuration Properties > General > Character Set choose "Use Multi-Byte Character Set"
Configuration Properties > C/C++ > Preprocessor > Preprocessor Definitions add _CRT_SECURE_NO_WARNINGS

Add glew.c to your project's Source Files, by which I mean right click on Source Files, choose Add Existing Item and select the file glew.c in the external\glew\src directory. Remember to include glew\include at this stage, and also in Linker > Input add the following two Additional Dependencies

opengl32.lib
glu32.lib

(For these two you don't need to worry about Additional Library Directories.
Visual Studio just knows where they are, they're part of Windows SDK, or something like that.)

Now add AntTweakBar and glfw (i.e., include the include directories, add Additional Library Directories where the .libs are, add the .libs to Additional Dependencies). Don't forget to include external\AntTweakBar\src because there are headers in there you need.

Hopefully your project builds successfully at this point. To run it though
you also have to copy AntTweakBar.dll from external\AntTweakBar\lib\debug and copy it into the Debug folder for your Solution (or wherever the ultimate .exe is).

Hope this helps. Hope I didn't leave anything out. Good luck!

**Comment by chenhonghua** [comment]
Hi:
I am a chinese . I am trying to work with libigl. I get some errores when I try to implement the Example 102. I have tried a lot, but there still exist errors. 

1>main.obj : error LNK2019: unresolved external symbol  "__declspec(dllimport) public: virtual int __thiscall CTwGraphOpenGLCore::Init(void)" (__imp_?Init@CTwGraphOpenGLCore@@UAEHXZ)，该符号在函数 "public: virtual int __thiscall igl::TextRenderer::Init(void)" (?Init@TextRenderer@igl@@UAEHXZ) 中被引用

1>main.obj : error LNK2019: unresolved external symbol  "__declspec(dllimport) public: virtual int __thiscall CTwGraphOpenGLCore::Shut(void)" (__imp_?Shut@CTwGraphOpenGLCore@@UAEHXZ)，该符号在函数 "public: virtual int __thiscall igl::TextRenderer::Shut(void)" (?Shut@TextRenderer@igl@@UAEHXZ) 中被引用

1>main.obj : error LNK2019: unresolved external symbol  "__declspec(dllimport) public: virtual void __thiscall CTwGraphOpenGLCore::BeginDraw(int,int)" (__imp_?BeginDraw@CTwGraphOpenGLCore@@UAEXHH@Z)，该符号在函数 "public: void __thiscall igl::TextRenderer::BeginDraw(class Eigen::Matrix<float,4,4,0,4,4> const &,class Eigen::Matrix<float,4,4,0,4,4> const &,class Eigen::Matrix<float,4,1,0,4,1> const &,float)" (?BeginDraw@TextRenderer@igl@@QAEXABV?$Matrix@M$03$03$0A@$03$03@Eigen@@0ABV?$Matrix@M$03$00$0A@$03$00@4@M@Z) 中被引用

1>main.obj : error LNK2019: unresolved external symbol  "__declspec(dllimport) public: virtual void __thiscall CTwGraphOpenGLCore::EndDraw(void)" (__imp_?EndDraw@CTwGraphOpenGLCore@@UAEXXZ)，该符号在函数 "public: virtual void __thiscall igl::TextRenderer::EndDraw(void)" (?EndDraw@TextRenderer@igl@@UAEXXZ) 中被引用

1>main.obj : error LNK2019: unresolved external symbol  "__declspec(dllimport) public: virtual void __thiscall CTwGraphOpenGLCore::DrawText(void *,int,int,unsigned int,unsigned int)" (__imp_?DrawText@CTwGraphOpenGLCore@@UAEXPAXHHII@Z)，该符号在函数 "public: void __thiscall igl::TextRenderer::DrawText(class Eigen::Matrix<double,3,1,0,3,1>,class Eigen::Matrix<double,3,1,0,3,1>,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?DrawText@TextRenderer@igl@@QAEXV?$Matrix@N$02$00$0A@$02$00@Eigen@@0ABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z) 中被引用

1>main.obj : error LNK2001: unresolved external symbol  "public: virtual void __thiscall CTwGraphOpenGLCore::BeginDraw(int,int)" (?BeginDraw@CTwGraphOpenGLCore@@UAEXHH@Z)

1>main.obj : error LNK2001: unresolved external symbol  "public: virtual void __thiscall CTwGraphOpenGLCore::BuildText(void *,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const *,unsigned int *,unsigned int *,int,struct CTexFont const *,int,int)" (?BuildText@CTwGraphOpenGLCore@@UAEXPAXPBV?$basic_string@DU?$char_traits@D@std@@V?
$allocator@D@2@@std@@PAI2HPBUCTexFont@@HH@Z)

1>main.obj : error LNK2001: unresolved external symbol  "public: virtual void __thiscall CTwGraphOpenGLCore::ChangeViewport(int,int,int,int,int,int)" (?ChangeViewport@CTwGraphOpenGLCore@@UAEXHHHHHH@Z)

1>main.obj : error LNK2001: unresolved external symbol  "public: virtual void __thiscall CTwGraphOpenGLCore::DeleteTextObj(void *)" (?DeleteTextObj@CTwGraphOpenGLCore@@UAEXPAX@Z)

1>main.obj : error LNK2001: unresolved external symbol  "public: virtual void __thiscall CTwGraphOpenGLCore::DrawLine(int,int,int,int,unsigned int,unsigned int,bool)" (?DrawLine@CTwGraphOpenGLCore@@UAEXHHHHII_N@Z)

1>main.obj : error LNK2001: unresolved external symbol "public: virtual void __thiscall CTwGraphOpenGLCore::DrawLine(int,int,int,int,unsigned int,bool)" (?DrawLine@CTwGraphOpenGLCore@@UAEXHHHHI_N@Z)

1>main.obj : error LNK2001: unresolved external symbol "public: virtual void __thiscall CTwGraphOpenGLCore::DrawRect(int,int,int,int,unsigned int)" (?DrawRect@CTwGraphOpenGLCore@@UAEXHHHHI@Z)

1>main.obj : error LNK2001: unresolved external symbol "public: virtual void __thiscall CTwGraphOpenGLCore::DrawRect(int,int,int,int,unsigned int,unsigned int,unsigned int,unsigned int)" (?DrawRect@CTwGraphOpenGLCore@@UAEXHHHHIIII@Z)

1>main.obj : error LNK2001:unresolved external symbol "public: virtual void __thiscall CTwGraphOpenGLCore::DrawText(void *,int,int,unsigned int,unsigned int)" (?DrawText@CTwGraphOpenGLCore@@UAEXPAXHHII@Z)

1>main.obj : error LNK2001: unresolved external symbol "public: virtual void __thiscall CTwGraphOpenGLCore::DrawTriangles(int,int *,unsigned int *,enum ITwGraph::Cull)" (?DrawTriangles@CTwGraphOpenGLCore@@UAEXHPAHPAIW4Cull@ITwGraph@@@Z)

1>main.obj : error LNK2001: unresolved external symbol "public: virtual void __thiscall CTwGraphOpenGLCore::EndDraw(void)" (?EndDraw@CTwGraphOpenGLCore@@UAEXXZ)

1>main.obj : error LNK2001: unresolved external symbol "public: virtual int __thiscall CTwGraphOpenGLCore::Init(void)" (?Init@CTwGraphOpenGLCore@@UAEHXZ)

1>main.obj : error LNK2001: unresolved external symbol "public: virtual bool __thiscall CTwGraphOpenGLCore::IsDrawing(void)" (?IsDrawing@CTwGraphOpenGLCore@@UAE_NXZ)

1>main.obj : error LNK2001: unresolved external symbol "public: virtual void * __thiscall CTwGraphOpenGLCore::NewTextObj(void)" (?NewTextObj@CTwGraphOpenGLCore@@UAEPAXXZ)

1>main.obj : error LNK2001: unresolved external symbol "public: virtual void __thiscall CTwGraphOpenGLCore::Restore(void)" (?Restore@CTwGraphOpenGLCore@@UAEXXZ)

1>main.obj : error LNK2001: unresolved external symbol "public: virtual void __thiscall CTwGraphOpenGLCore::RestoreViewport(void)" (?RestoreViewport@CTwGraphOpenGLCore@@UAEXXZ)

1>main.obj : error LNK2001: unresolved external symbol "public: virtual void __thiscall CTwGraphOpenGLCore::SetScissor(int,int,int,int)" (?SetScissor@CTwGraphOpenGLCore@@UAEXHHHH@Z)

1>main.obj : error LNK2001: unresolved external symbol "public: virtual int __thiscall CTwGraphOpenGLCore::Shut(void)" (?Shut@CTwGraphOpenGLCore@@UAEHXZ)

1>main.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) struct CTexFont * g_DefaultNormalFont" (__imp_?g_DefaultNormalFont@@3PAUCTexFont@@A)

Sincerely need your help.

**Comment by danielepanozzo** [comment]
These errors are probably caused by using the binary of a standard version of anttweakbar. For libigl (windows only) you need to use the anttweakbar that is included in the libigl repository under external.

**Comment by chenhonghua** [comment]
Thank you for your response. I'v used the anttweakbar that is included in the libigl repository under external. It doesn't work. So, I tried to search CTwGraphOpenGLCore in libigl according the error information. But I have not found it. I think if I find the CTwGraphOpenGLCore, the problem may be solved.

**Comment by chenhonghua** [comment]
@danielepanozzo   
Sorry, Please excuse my carelessness. I'v found CTwGraphOpenGLCore in external\AntTweakBar\src\TwOpenGLCore.h.  But why it still dosen't work although i'v include the src directory?

**Comment by chenhonghua** [comment]
@cap257zero Hi,
 I'v tried what you said, and complied the Example 102 successfully. But I still cannot see the expected result. It just shows the imfomation that " The requested client API version is available".

**Comment by cap257zero** [comment]
I have limited experience with this stuff so I'm just guessing, but maybe it's got something to do with the opengl32 and glu32 libs. What Windows version do you have? And do you have Windows SDK installed?

Also just checking but I assume the error message says "UNavaliable" right?

**Comment by chenhonghua** [comment]
![1](https://cloud.githubusercontent.com/assets/11238777/6860198/00432c66-d460-11e4-818b-d672d37e4781.png)
@cap257zero : 
As you can see above, i tried to execute the “exe”. It just indicate the information "The  requested ...". 
"请按任意键继续" is equal to "Press any key to continue". Don't be care about that. And my computer system is Win7(32), the visual stdio is 2013. 
I updated my opengl32 and glu32 libs. It still shows the information as the picture shows.  I am almost  crazy about it. But I think I'm very close to the answer. 
Sincerely expect your suggestions.

**Comment by danielepanozzo** [comment]
The tutorial needs opengl 3.3 or newer. Is your driver/video card supporting it? It could be that the driver is not able to open a 3.3 opengl context.

**Comment by chenhonghua** [comment]
@danielepanozzo @cap257zero 
Thank you very much. I change my computer that support the opengl 3.3 and run the example in tutorial successfull. Thank you for your patient guidance again.

**Comment by TRYuan** [comment]
@chenhonghua , 能否给我您的邮箱，我也遇到与你类似的问题。

**Comment by chenhonghua** [comment]
@TRYuan  chenhhcn@163.com
