### ISSUE TITLE
compilation problem in windows+matlab+cgal

### ISSUE THREAD

**Issue by noadag** [libigl/libigl#39]
Hi again,

As I am now looking to use the mesh_boolean capabilities, I have set up CGAL and its dependencies (hopefully), and dangerously proceeded to attempt to compile my mex file in the following way:

```
mex -O -DIGL_HEADER_ONLY ...
    -ID:\noa\igl\libigl-master\include\ ...
    -ID:\noa\igl\libigl-master\include\igl\boolean\ ...
    -ID:\noa\igl\eigen3 ...
    -ID:\noa\igl\eigen3\unsupported ...
    -ID:\boost_1_57_0 ...
    -I"C:\Program Files\CGAL-4.5.1\include" ...
    -I"C:\Program Files\CGAL-4.5.1\build\include" ...
    -L"C:\Program Files\CGAL-4.5.1\build\lib" -lCGAL_Core-vc100-mt-4.5.1 ...
    -I"C:\Program Files\CGAL-4.5.1\auxiliary\gmp\include" ...
    mesh_boolean_mex.cpp
```

I am then getting the following errors, preceded by a seemingly relevant warning:

```
d:\noa\igl\libigl-master\include\igl\cgal\SelfIntersectMesh.h(217) : warning C4346:
'igl::SelfIntersectMesh<Kernel,DerivedV,DerivedF,DerivedVV,DerivedFF,DerivedIF,DerivedJ,DerivedIM>::Box' : dependent
name is not a type
        prefix with 'typename' to indicate a type
        d:\noa\igl\libigl-master\include\igl\cgal\SelfIntersectMesh.h(219) : see reference to class template
        instantiation
        'igl::SelfIntersectMesh<Kernel,DerivedV,DerivedF,DerivedVV,DerivedFF,DerivedIF,DerivedJ,DerivedIM>' being
        compiled

d:\noa\igl\libigl-master\include\igl\cgal\SelfIntersectMesh.h(217) : error C2061: syntax error : identifier 'Box'

d:\noa\igl\libigl-master\include\igl\cgal\SelfIntersectMesh.h(286) : error C2244:
'igl::SelfIntersectMesh<Kernel,DerivedV,DerivedF,DerivedVV,DerivedFF,DerivedIF,DerivedJ,DerivedIM>::box_intersect' :
unable to match function definition to an existing declaration
        definition
        'void
        igl::SelfIntersectMesh<Kernel,DerivedV,DerivedF,DerivedVV,DerivedFF,DerivedIF,DerivedJ,DerivedIM>::box_intersect(igl::SelfIntersectMesh<Kernel,DerivedV,DerivedF,DerivedVV,DerivedFF,DerivedIF,DerivedJ,DerivedIM>
        *,const SelfIntersectMesh<Kernel,DerivedV,DerivedF,DerivedVV,DerivedFF,DerivedIF,DerivedJ,DerivedIM>::Box
        &,const SelfIntersectMesh<Kernel,DerivedV,DerivedF,DerivedVV,DerivedFF,DerivedIF,DerivedJ,DerivedIM>::Box &)'
        existing declarations
        'void
        igl::SelfIntersectMesh<Kernel,DerivedV,DerivedF,DerivedVV,DerivedFF,DerivedIF,DerivedJ,DerivedIM>::box_intersect(igl::SelfIntersectMesh<Kernel,DerivedV,DerivedF,DerivedVV,DerivedFF,DerivedIF,DerivedJ,DerivedIM>
        *)'
        'void
        igl::SelfIntersectMesh<Kernel,DerivedV,DerivedF,DerivedVV,DerivedFF,DerivedIF,DerivedJ,DerivedIM>::box_intersect(const
        CGAL::Box_intersection_d::Box_with_handle_d<double,3,vector<CGAL::Triangle_3<R_>>::iterator> &,const
        CGAL::Box_intersection_d::Box_with_handle_d<double,3,vector<CGAL::Triangle_3<R_>>::iterator> &)'
```

I suspect it's a compiler issue, since I tried compiling it in Linux and did not have this problem. However, since the CGAL process for Linux is different (and consequently also the mex command that I used), it may also be some CGAL component (or dependency) that I am missing in Windows.
Any ideas?

**Comment by alecjacobson** [comment]
This might be as simple as MVC and GCC disagreeing about what the type of `Box` is. I just pushed a small change (402dd571c0ea32d5356a9bc644be6fa0eda842a7) that might resolve this.

**Comment by noadag** [comment]
Thanks, that took care of it!
It now complains about:
```
d:\noa\igl\libigl-master\include\igl\cgal\SelfIntersectMesh.h(354) : error C2276: '&' : illegal operation on bound
member function expression
```

Any way around that? Those MS compilers are so touchy...

**Comment by noadag** [comment]
Oh, solved it by adding ```SelfIntersectMesh::``` before box_intersect.
Now looking into a new error... :)

**Comment by noadag** [comment]
Ok, so after adding the above I'm getting this monstrosity (I broke it into pieces, but I suppose only the first part is interesting): 

```
d:\noa\igl\libigl-master\include\igl\cgal\SelfIntersectMesh.h(354) : error C2668: 'boost::bind' : ambiguous call to overloaded function
        D:\boost_1_57_0\boost/bind/bind_mf_cc.hpp(67): could be
        'boost::_bi::bind_t<void,boost::_mfi::mf2<void,igl::SelfIntersectMesh<Kernel,DerivedV,DerivedF,DerivedVV,DerivedFF,DerivedIF,DerivedJ,DerivedIM>,const
        CGAL::Box_intersection_d::Box_with_handle_d<double,3,std::_Vector_iterator<std::_Vector_val<std::_Simple_types<CGAL::Triangle_3<Kernel_>>>>,CGAL::Box_intersection_d::ID_FROM_HANDLE>
        &,const
        CGAL::Box_intersection_d::Box_with_handle_d<double,3,std::_Vector_iterator<std::_Vector_val<std::_Simple_types<CGAL::Triangle_3<Kernel_>>>>,CGAL::Box_intersection_d::ID_FROM_HANDLE>
        &>,boost::_bi::list3<boost::_bi::value<T>,boost::arg<1>,boost::arg<2>>>
        boost::bind<void,igl::SelfIntersectMesh<Kernel,DerivedV,DerivedF,DerivedVV,DerivedFF,DerivedIF,DerivedJ,DerivedIM>,const
        CGAL::Box_intersection_d::Box_with_handle_d<double,3,std::_Vector_iterator<std::_Vector_val<std::_Simple_types<CGAL::Triangle_3<Kernel_>>>>,CGAL::Box_intersection_d::ID_FROM_HANDLE>&,const
        CGAL::Box_intersection_d::Box_with_handle_d<double,3,std::_Vector_iterator<std::_Vector_val<std::_Simple_types<CGAL::Triangle_3<Kernel_>>>>,CGAL::Box_intersection_d::ID_FROM_HANDLE>&,igl::SelfIntersectMesh<Kernel,DerivedV,DerivedF,DerivedVV,DerivedFF,DerivedIF,DerivedJ,DerivedIM>*,boost::arg<1>,boost::arg<2>>(R
        (__cdecl igl::SelfIntersectMesh<Kernel,DerivedV,DerivedF,DerivedVV,DerivedFF,DerivedIF,DerivedJ,DerivedIM>::* )(B1,B2),A1,A2,A3)'
        with
        [
            DerivedV=Eigen::Matrix<double,-1,3,0,-1,3>
,            DerivedF=Eigen::Matrix<int,-1,3,0,-1,3>
,            DerivedVV=Eigen::Matrix<double,-1,3,0,-1,3>
,            DerivedFF=Eigen::Matrix<int,-1,3,0,-1,3>
,            DerivedIF=Eigen::Matrix<int,-1,2,0,-1,2>
,            DerivedJ=Eigen::Matrix<int,-1,1,0,-1,1>
,            DerivedIM=Eigen::Matrix<int,-1,1,0,-1,1>
,            Kernel_=CGAL::Epick
,
T=igl::SelfIntersectMesh<Kernel,Eigen::Matrix<double,-1,3,0,-1,3>,Eigen::Matrix<int,-1,3,0,-1,3>,Eigen::Matrix<double,-1,3,0,-1,3>,Eigen::Matrix<int,-1,3,0,-1,3>,Eigen::Matrix<int,-1,2,0,-1,2>,Eigen::Matrix<int,-1,1,0,-1,1>,Eigen::Matrix<int,-1,1,0,-1,1>>
*
,            R=void
,            B1=const
CGAL::Box_intersection_d::Box_with_handle_d<double,3,std::_Vector_iterator<std::_Vector_val<std::_Simple_types<CGAL::Triangle_3<CGAL::Epick>>>>,CGAL::Box_intersection_d::ID_FROM_HANDLE>
&
,            B2=const
CGAL::Box_intersection_d::Box_with_handle_d<double,3,std::_Vector_iterator<std::_Vector_val<std::_Simple_types<CGAL::Triangle_3<CGAL::Epick>>>>,CGAL::Box_intersection_d::ID_FROM_HANDLE>
&
,
A1=igl::SelfIntersectMesh<Kernel,Eigen::Matrix<double,-1,3,0,-1,3>,Eigen::Matrix<int,-1,3,0,-1,3>,Eigen::Matrix<double,-1,3,0,-1,3>,Eigen::Matrix<int,-1,3,0,-1,3>,Eigen::Matrix<int,-1,2,0,-1,2>,Eigen::Matrix<int,-1,1,0,-1,1>,Eigen::Matrix<int,-1,1,0,-1,1>>
*
,            A2=boost::arg<1>
,            A3=boost::arg<2>
        ]
        D:\boost_1_57_0\boost/bind/bind_cc.hpp(46): or       'boost::_bi::bind_t<void,void (__cdecl
        *)(igl::SelfIntersectMesh<Kernel,DerivedV,DerivedF,DerivedVV,DerivedFF,DerivedIF,DerivedJ,DerivedIM> *,const
```
```        CGAL::Box_intersection_d::Box_with_handle_d<double,3,std::_Vector_iterator<std::_Vector_val<std::_Simple_types<CGAL::Triangle_3<Kernel_>>>>,CGAL::Box_intersection_d::ID_FROM_HANDLE>
        &,const
        CGAL::Box_intersection_d::Box_with_handle_d<double,3,std::_Vector_iterator<std::_Vector_val<std::_Simple_types<CGAL::Triangle_3<Kernel_>>>>,CGAL::Box_intersection_d::ID_FROM_HANDLE>
        &),boost::_bi::list3<boost::_bi::value<T>,boost::arg<1>,boost::arg<2>>>
        boost::bind<void,igl::SelfIntersectMesh<Kernel,DerivedV,DerivedF,DerivedVV,DerivedFF,DerivedIF,DerivedJ,DerivedIM>*,const
        CGAL::Box_intersection_d::Box_with_handle_d<double,3,std::_Vector_iterator<std::_Vector_val<std::_Simple_types<CGAL::Triangle_3<Kernel_>>>>,CGAL::Box_intersection_d::ID_FROM_HANDLE>&,const
        CGAL::Box_intersection_d::Box_with_handle_d<double,3,std::_Vector_iterator<std::_Vector_val<std::_Simple_types<CGAL::Triangle_3<Kernel_>>>>,CGAL::Box_intersection_d::ID_FROM_HANDLE>&,igl::SelfIntersectMesh<Kernel,DerivedV,DerivedF,DerivedVV,DerivedFF,DerivedIF,DerivedJ,DerivedIM>*,boost::arg<1>,boost::arg<2>>(R
        (__cdecl *)(B1,B2,B3),A1,A2,A3)'
        with
        [
            DerivedV=Eigen::Matrix<double,-1,3,0,-1,3>
,            DerivedF=Eigen::Matrix<int,-1,3,0,-1,3>
,            DerivedVV=Eigen::Matrix<double,-1,3,0,-1,3>
,            DerivedFF=Eigen::Matrix<int,-1,3,0,-1,3>
,            DerivedIF=Eigen::Matrix<int,-1,2,0,-1,2>
,            DerivedJ=Eigen::Matrix<int,-1,1,0,-1,1>
,            DerivedIM=Eigen::Matrix<int,-1,1,0,-1,1>
,            Kernel_=CGAL::Epick
,
T=igl::SelfIntersectMesh<Kernel,Eigen::Matrix<double,-1,3,0,-1,3>,Eigen::Matrix<int,-1,3,0,-1,3>,Eigen::Matrix<double,-1,3,0,-1,3>,Eigen::Matrix<int,-1,3,0,-1,3>,Eigen::Matrix<int,-1,2,0,-1,2>,Eigen::Matrix<int,-1,1,0,-1,1>,Eigen::Matrix<int,-1,1,0,-1,1>>
*
,            R=void
,
B1=igl::SelfIntersectMesh<Kernel,Eigen::Matrix<double,-1,3,0,-1,3>,Eigen::Matrix<int,-1,3,0,-1,3>,Eigen::Matrix<double,-1,3,0,-1,3>,Eigen::Matrix<int,-1,3,0,-1,3>,Eigen::Matrix<int,-1,2,0,-1,2>,Eigen::Matrix<int,-1,1,0,-1,1>,Eigen::Matrix<int,-1,1,0,-1,1>>
*
,            B2=const
CGAL::Box_intersection_d::Box_with_handle_d<double,3,std::_Vector_iterator<std::_Vector_val<std::_Simple_types<CGAL::Triangle_3<CGAL::Epick>>>>,CGAL::Box_intersection_d::ID_FROM_HANDLE>
&
,            B3=const
CGAL::Box_intersection_d::Box_with_handle_d<double,3,std::_Vector_iterator<std::_Vector_val<std::_Simple_types<CGAL::Triangle_3<CGAL::Epick>>>>,CGAL::Box_intersection_d::ID_FROM_HANDLE>
&
,
A1=igl::SelfIntersectMesh<Kernel,Eigen::Matrix<double,-1,3,0,-1,3>,Eigen::Matrix<int,-1,3,0,-1,3>,Eigen::Matrix<double,-1,3,0,-1,3>,Eigen::Matrix<int,-1,3,0,-1,3>,Eigen::Matrix<int,-1,2,0,-1,2>,Eigen::Matrix<int,-1,1,0,-1,1>,Eigen::Matrix<int,-1,1,0,-1,1>>
*
,            A2=boost::arg<1>
,            A3=boost::arg<2>
        ]
        while trying to match the argument list '(overloaded-function,
```
```
  igl::SelfIntersectMesh<Kernel,DerivedV,DerivedF,DerivedVV,DerivedFF,DerivedIF,DerivedJ,DerivedIM> *const , boost::arg<1>,
        boost::arg<2>)'
        with
        [
            DerivedV=Eigen::Matrix<double,-1,3,0,-1,3>
,            DerivedF=Eigen::Matrix<int,-1,3,0,-1,3>
,            DerivedVV=Eigen::Matrix<double,-1,3,0,-1,3>
,            DerivedFF=Eigen::Matrix<int,-1,3,0,-1,3>
,            DerivedIF=Eigen::Matrix<int,-1,2,0,-1,2>
,            DerivedJ=Eigen::Matrix<int,-1,1,0,-1,1>
,            DerivedIM=Eigen::Matrix<int,-1,1,0,-1,1>
        ]
        d:\noa\igl\libigl-master\include\igl\cgal\SelfIntersectMesh.h(313) : while compiling class template member function
        'igl::SelfIntersectMesh<Kernel,DerivedV,DerivedF,DerivedVV,DerivedFF,DerivedIF,DerivedJ,DerivedIM>::SelfIntersectMesh(const
        Eigen::PlainObjectBase<Eigen::Matrix<double,-1,3,0,-1,3>> &,const Eigen::PlainObjectBase<Eigen::Matrix<int,-1,3,0,-1,3>> &,const
        igl::RemeshSelfIntersectionsParam &,Eigen::PlainObjectBase<Eigen::Matrix<double,-1,3,0,-1,3>>
        &,Eigen::PlainObjectBase<Eigen::Matrix<int,-1,3,0,-1,3>> &,Eigen::PlainObjectBase<Eigen::Matrix<int,-1,2,0,-1,2>>
        &,Eigen::PlainObjectBase<Eigen::Matrix<int,-1,1,0,-1,1>> &,Eigen::PlainObjectBase<Eigen::Matrix<int,-1,1,0,-1,1>> &)'
        with
        [
            DerivedV=Eigen::Matrix<double,-1,3,0,-1,3>
,            DerivedF=Eigen::Matrix<int,-1,3,0,-1,3>
,            DerivedVV=Eigen::Matrix<double,-1,3,0,-1,3>
,            DerivedFF=Eigen::Matrix<int,-1,3,0,-1,3>
,            DerivedIF=Eigen::Matrix<int,-1,2,0,-1,2>
,            DerivedJ=Eigen::Matrix<int,-1,1,0,-1,1>
,            DerivedIM=Eigen::Matrix<int,-1,1,0,-1,1>
        ]
        d:\noa\igl\libigl-master\include\igl\cgal\remesh_self_intersections.cpp(59) : see reference to function template instantiation
        'igl::SelfIntersectMesh<Kernel,DerivedV,DerivedF,DerivedVV,DerivedFF,DerivedIF,DerivedJ,DerivedIM>::SelfIntersectMesh(const
        Eigen::PlainObjectBase<Eigen::Matrix<double,-1,3,0,-1,3>> &,const Eigen::PlainObjectBase<Eigen::Matrix<int,-1,3,0,-1,3>> &,const
        igl::RemeshSelfIntersectionsParam &,Eigen::PlainObjectBase<Eigen::Matrix<double,-1,3,0,-1,3>>
        &,Eigen::PlainObjectBase<Eigen::Matrix<int,-1,3,0,-1,3>> &,Eigen::PlainObjectBase<Eigen::Matrix<int,-1,2,0,-1,2>>
        &,Eigen::PlainObjectBase<Eigen::Matrix<int,-1,1,0,-1,1>> &,Eigen::PlainObjectBase<Eigen::Matrix<int,-1,1,0,-1,1>> &)' being compiled
        with
        [
            DerivedV=Eigen::Matrix<double,-1,3,0,-1,3>
,            DerivedF=Eigen::Matrix<int,-1,3,0,-1,3>
,            DerivedVV=Eigen::Matrix<double,-1,3,0,-1,3>
,            DerivedFF=Eigen::Matrix<int,-1,3,0,-1,3>
,            DerivedIF=Eigen::Matrix<int,-1,2,0,-1,2>
,            DerivedJ=Eigen::Matrix<int,-1,1,0,-1,1>
,            DerivedIM=Eigen::Matrix<int,-1,1,0,-1,1>
        ]
        d:\noa\igl\libigl-master\include\igl\cgal\remesh_self_intersections.cpp(59) : see reference to class template instantiation
        'igl::SelfIntersectMesh<Kernel,DerivedV,DerivedF,DerivedVV,DerivedFF,DerivedIF,DerivedJ,DerivedIM>' being compiled
        with
        [
            DerivedV=Eigen::Matrix<double,-1,3,0,-1,3>
,            DerivedF=Eigen::Matrix<int,-1,3,0,-1,3>
,            DerivedVV=Eigen::Matrix<double,-1,3,0,-1,3>
,            DerivedFF=Eigen::Matrix<int,-1,3,0,-1,3>
,            DerivedIF=Eigen::Matrix<int,-1,2,0,-1,2>
,            DerivedJ=Eigen::Matrix<int,-1,1,0,-1,1>
,            DerivedIM=Eigen::Matrix<int,-1,1,0,-1,1>
        ]
        d:\noa\igl\libigl-master\include\igl\boolean\mesh_boolean.cpp(142) : see reference to function template instantiation 'void
        igl::remesh_self_intersections<Eigen::Matrix<double,-1,3,0,-1,3>,Eigen::Matrix<int,-1,3,0,-1,3>,Eigen::Matrix<double,-1,3,0,-1,3>,Eigen::Matrix<int,-1,3,0,-1,3>,Eigen::Matrix<int,-1,2,0,-1,2>,Eigen::Matrix<int,-1,1,0,-1,1>,Eigen::Matrix<int,-1,1,0,-1,1>>(const
        Eigen::PlainObjectBase<Eigen::Matrix<double,-1,3,0,-1,3>> &,const Eigen::PlainObjectBase<Eigen::Matrix<int,-1,3,0,-1,3>> &,const
        igl::RemeshSelfIntersectionsParam &,Eigen::PlainObjectBase<Eigen::Matrix<double,-1,3,0,-1,3>>
        &,Eigen::PlainObjectBase<Eigen::Matrix<int,-1,3,0,-1,3>> &,Eigen::PlainObjectBase<Eigen::Matrix<int,-1,2,0,-1,2>>
        &,Eigen::PlainObjectBase<Eigen::Matrix<int,-1,1,0,-1,1>> &,Eigen::PlainObjectBase<Eigen::Matrix<int,-1,1,0,-1,1>> &)' being compiled
        d:\noa\igl\libigl-master\include\igl\boolean\mesh_boolean.cpp(35) : see reference to function template instantiation 'void
        igl::mesh_boolean<Eigen::Matrix<double,-1,-1,0,-1,-1>,Eigen::Matrix<int,-1,-1,0,-1,-1>,Eigen::Matrix<double,-1,-1,0,-1,-1>,Eigen::Matrix<int,-1,-1,0,-1,-1>,Eigen::Matrix<double,-1,-1,0,-1,-1>,Eigen::Matrix<int,-1,-1,0,-1,-1>,Eigen::Matrix<int,-1,-1,0,-1,-1>>(const
        Eigen::PlainObjectBase<Eigen::Matrix<double,-1,-1,0,-1,-1>> &,const Eigen::PlainObjectBase<Eigen::Matrix<int,-1,-1,0,-1,-1>> &,const
        Eigen::PlainObjectBase<Eigen::Matrix<double,-1,-1,0,-1,-1>> &,const Eigen::PlainObjectBase<Eigen::Matrix<int,-1,-1,0,-1,-1>> &,const
        igl::MeshBooleanType &,const std::function<void (const Eigen::Matrix<double,-1,3,0,-1,3> &,const Eigen::Matrix<int,-1,3,0,-1,3>
        &,Eigen::Matrix<double,-1,3,0,-1,3> &,Eigen::Matrix<int,-1,3,0,-1,3> &,Eigen::Matrix<int,-1,1,0,-1,1> &)>
        &,Eigen::PlainObjectBase<Eigen::Matrix<double,-1,-1,0,-1,-1>> &,Eigen::PlainObjectBase<Eigen::Matrix<int,-1,-1,0,-1,-1>>
        &,Eigen::PlainObjectBase<Eigen::Matrix<int,-1,-1,0,-1,-1>> &)' being compiled
```

**Comment by alecjacobson** [comment]
I pushed a change that hopefully resolves this issue. It also removes the
explicit dependency of SelfIntersectMesh.h on boost (using c++11
`<functional>` instead).

**Comment by noadag** [comment]
That does the trick, thanks!
I'm now trying to resolve some other compiler issue, so I'll update once I'm in the clear so that this thread can be closed.

**Comment by noadag** [comment]
Happy to report that it now compiles and runs :)
Now that I see what it does I am reconsidering my steps. Since in my setting I have cages that may be partially contained within the mesh, it seems as though the mesh union does not resolve my problem. In such a case, the union will remove the parts of the cage that are contained within the mesh, and therefore, the edges of these parts will be absent when the time comes to perform ```boundary_conditions```. So, what if I use the face intersection resolver instead of the union? I can have a concatenation of the mesh and the cage given as input to the resolver and get an intersection-free mesh for Tetgen that will include both the mesh and the cage. Another possibility is to just have the cage as input to Tetgen and then determine the weights for the mesh vertices based on barycentric coordinates. Mesh connectivity will be lost of course, but is it a major issue assuming that the mesh is almost convex? 
Thanks!

**Comment by alecjacobson** [comment]
Yes, I'm sorry I was mistaken. Indeed what you want is to pass _all_
vertices and faces of the intersection-resolve to TetGen as constraints to
conform to. The surface of this "resolve" will match the union. But you do
want all the internal facets, too.

So, yes. The easiest way to achieve this right now is via
`igl::mesh_boolean` with `type=MESH_BOOLEAN_TYPE_RESOLVE`. For this to work
correctly with Tetgen you should verify that your input mesh and cage are
watertight.

The barycentric interpolation idea is also OK, but might not give you the
"crispest" weights at your mesh vertices. This might be a good route if you
run into robustness issues with TeGen. BTW, You can find which tet a point
lies in with `igl::in_element`and its corresponding barycentric coordinates
with `igl::barycentric_coordinates`.

**Comment by noadag** [comment]
Ok, great.
Thanks for all the help and advice!
