### ISSUE TITLE
QSlim Producing Degenerate Meshes

### ISSUE THREAD

**Issue by KermMartian** [libigl/libigl#738]
Using QSlim mesh decimation on a planar mesh produces some triangles with normals inverted, and hence overlapping triangles adjacent to those inverted triangles. To debug, I added a wrapper around the QSlim `cost_and_placement()` method that checks the placement point `p` that it computes. I found that the edge collapses that produce those inverted triangles picks a placement that is beyond the endpoints of the original edge. For example:

```
Placement for 20: original points at (0.000000, 3.000000, 0.850531) and (-0.000721, 1.852707, 0.974038)
Final point at (-0.026019, 2.853664, 0.991565)
Just collapsed edge 20 (23 <-> 29)
Face 1 is now upside-down!
```

Let me know if there's anything else I can provide, like a MWE. I've been able to reproduce this on simple 12-triangle terrain-like rectangular meshes.

**Comment by KermMartian** [comment]
Apologies for bumping this; I wanted to specifically see if @alecjacobson had any ideas on this, for obvious reasons. Thanks in advance!

**Comment by alecjacobson** [comment]
Strictly speaking the classic quadric error metric (I believe this is what I implemented) degenerates in the planar case: any point on the plane is an equally good placement. A reasonable solution would be to sprinkle in another energy that pulls the vertex toward (for example) the midpoint of the edge being collapsed. It's probably enough to add this energy with a very low weight (1e-7) so that it only really "activates" in these degenerate cases.

**Comment by KermMartian** [comment]
I should clarify that this is a mesh that represents a single surface (properly connected to the infinite vertex at its edges), but is not strictly a flat plane; every point has a random Z coordinate between 0 and 1. The weight you suggest helps (iff I increase the magnitude to equivalent to the average edge length between vertices in the mesh), but still does not prevent very thin inverted triangles. I added a whole bunch of safety and debugging around the existing QSlim code (for example, explicitly prevent it from collapsing edges that touch the boundary, explicitly prevent it from collapsing edges with anything other than exactly 2 shared neighbor vertices, etc.). I now notice that the problem only occurs when QSlim goes to collapse a second edge, which makes me think that there's a bug in the current algorithm: not properly re-computing the cost of edges affected by a collapse.

@alecjacobson, please advise if this is true, and if I should ask you to address it or for guidance in how and where to repair it (and PR the fix) myself. Thanks in advance.

**Comment by alecjacobson** [comment]
I'm fairly confident that edge costs are being updated _for manifold_
meshes. If it's not manifold, I'm not sure what would happened, but I'm
fairly sure it won't be right.

**Comment by KermMartian** [comment]
My understanding from the documentation is that calling `igl::connect_boundary_to_infinity()` on a non-manifold mesh should make the decimation work, because structurally the mesh is then closed through infinite vertex?

**Comment by alecjacobson** [comment]
The immediate issue is that the collapse edge routine is assuming manifoldness when finding adjacent faces/vertices. This will be simply wrong for faces near non-manifold edges.

**Comment by KermMartian** [comment]
I've been manually solving that by explicitly setting the cost of collapsing edges that touch a boundary vertex to infinity; the edges in question have been on the interior of the "surface".
